// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.5.1_@types+node@18.14.6_eslint@8.41.0_rollup@3.22.0_typescript@5.0.4/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.5.1_@types+node@18.14.6_eslint@8.41.0_rollup@3.22.0_typescript@5.0.4/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.5.1_@types+node@18.14.6_eslint@8.41.0_rollup@3.22.0_typescript@5.0.4/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.5.1_@types+node@18.14.6_eslint@8.41.0_rollup@3.22.0_typescript@5.0.4/node_modules/nuxt/dist/app/plugins/router").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.5.1_@types+node@18.14.6_eslint@8.41.0_rollup@3.22.0_typescript@5.0.4/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
